"""empty message

Revision ID: 16528bca5771
Revises: 7690b8254705
Create Date: 2025-07-01 11:11:18.607879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16528bca5771'
down_revision = '7690b8254705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_management_log', schema=None) as batch_op:
        batch_op.alter_column('log_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)
        #batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_management_log', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['item_id'])
        batch_op.alter_column('log_id',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
