"""modified the items table

Revision ID: 1b227c8e7ecf
Revises: 4899c12a9a09
Create Date: 2025-07-28 02:37:32.255016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b227c8e7ecf'
down_revision = '4899c12a9a09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Float(), nullable=True))
        batch_op.drop_column('discount_price')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_price', sa.FLOAT(), nullable=True))
        batch_op.drop_column('discount')

    # ### end Alembic commands ###
