"""Updating the user profile table

Revision ID: 1f6e8d5821ac
Revises: 75ad28022069
Create Date: 2025-07-15 13:47:37.435650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f6e8d5821ac'
down_revision = '75ad28022069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_auth_logs',
    sa.Column('log_id', sa.String(length=6), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('usersProfiles',
    sa.Column('userp_id', sa.String(length=6), nullable=False),
    sa.Column('user_id', sa.String(length=6), nullable=False),
    sa.Column('full_name', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('profile_pic', sa.String(length=200), nullable=False),
    sa.Column('invite_code', sa.String(length=30), nullable=False),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('userp_id')
    )
    op.drop_table('users_profiles')
    op.drop_table('user_aunthet_logs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_aunthet_logs',
    sa.Column('log_id', sa.VARCHAR(length=6), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('action', sa.VARCHAR(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('users_profiles',
    sa.Column('userp_id', sa.VARCHAR(length=7), nullable=False),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('full_name', sa.VARCHAR(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=30), nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=False),
    sa.Column('profile_pic', sa.VARCHAR(length=200), nullable=False),
    sa.Column('invite_code', sa.VARCHAR(), nullable=False),
    sa.Column('marketin_opt_in', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('userp_id')
    )
    op.drop_table('usersProfiles')
    op.drop_table('user_auth_logs')
    # ### end Alembic commands ###
