"""Updating the items table

Revision ID: 339dfee6c81c
Revises: 6a664ef54444
Create Date: 2025-07-17 17:31:39.389346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '339dfee6c81c'
down_revision = '6a664ef54444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('category')

    # ### end Alembic commands ###
