"""Added the ortractional table

Revision ID: 344772610188
Revises: 1b227c8e7ecf
Create Date: 2025-07-28 09:51:42.544759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '344772610188'
down_revision = '1b227c8e7ecf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items_transactions',
    sa.Column('transaction_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('quantity_changed', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items_transactions')
    # ### end Alembic commands ###
