"""Corrected the Password Column

Revision ID: 4280ba0b9b9f
Revises: e4ddd882aad7
Create Date: 2025-07-11 05:10:59.980574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4280ba0b9b9f'
down_revision = 'e4ddd882aad7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=30), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=30), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###
