"""initial scheam

Revision ID: 4ca1b4ec966a
Revises: 
Create Date: 2025-05-13 13:20:01.202754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ca1b4ec966a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('date_registered', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('items',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False, unique=False),
    sa.Column('price', sa.Float(), nullable=False, unique=False),
    sa.Column('barcode', sa.String(length=12), nullable=False, unique=True),
    sa.Column('description', sa.String(length=1024), nullable=False, unique=True),
    sa.Column('quantity', sa.Integer(), nullable=False, unique=False),
    sa.Column('added_by', sa.String(length=30), nullable=False, unique=False),
    sa.Column('date_added', sa.DateTime(), nullable=False, default=sa.func.current_timestamp()),
    sa.ForeignKeyConstraint(['added_by'], ['admins.admin_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('description'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('items')
    op.drop_table('admins')
    # ### end Alembic commands ###
