"""removed FK logtable.itemid

Revision ID: 68d933a7c27f
Revises: 16528bca5771
Create Date: 2025-07-01 11:55:30.985371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68d933a7c27f'
down_revision = '16528bca5771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    None

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_management_log', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['item_id'])

    # ### end Alembic commands ###
