"""creating  the initial schemas

Revision ID: 703e84ed8d3d
Revises: 
Create Date: 2025-07-10 16:46:44.011066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '703e84ed8d3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password', sa.String(length=30), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_super_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('date_registered', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('admin_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('site_visit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.String(length=256), nullable=True),
    sa.Column('visited_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('password_hash', sa.String(length=30), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('profile_pic', sa.String(length=200), nullable=True),
    sa.Column('invite_code', sa.String(), nullable=True),
    sa.Column('marketin_opt_in', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    op.create_table('admin_action_log',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_admin_id', sa.String(), nullable=False),
    sa.Column('performed_by_admin_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by_admin_id'], ['admins.admin_id'], ),
    sa.ForeignKeyConstraint(['target_admin_id'], ['admins.admin_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('item_management_log',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('admin_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.admin_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('items',
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('barcode', sa.String(length=12), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('added_by', sa.String(length=6), nullable=False),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['added_by'], ['admins.admin_id'], ),
    sa.PrimaryKeyConstraint('item_id'),
    sa.UniqueConstraint('barcode'),
    sa.UniqueConstraint('description')
    )
    op.create_table('user_aunthet_logs',
    sa.Column('log_id', sa.String(length=6), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_aunthet_logs')
    op.drop_table('items')
    op.drop_table('item_management_log')
    op.drop_table('admin_action_log')
    op.drop_table('users')
    op.drop_table('site_visit_logs')
    op.drop_table('admins')
    # ### end Alembic commands ###
