"""Updated the user profile table

Revision ID: 75ad28022069
Revises: 4280ba0b9b9f
Create Date: 2025-07-12 20:04:11.659388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75ad28022069'
down_revision = '4280ba0b9b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_profiles',
    sa.Column('userp_id', sa.String(length=7), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('profile_pic', sa.String(length=200), nullable=False),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('marketin_opt_in', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('userp_id')
    )
    op.drop_table('users_profile')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_profile',
    sa.Column('userp_id', sa.VARCHAR(length=7), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.VARCHAR(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=30), nullable=False),
    sa.Column('location', sa.VARCHAR(length=200), nullable=False),
    sa.Column('date_of_birth', sa.DATE(), nullable=False),
    sa.Column('profile_pic', sa.VARCHAR(length=200), nullable=False),
    sa.Column('invite_code', sa.VARCHAR(), nullable=False),
    sa.Column('marketin_opt_in', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('userp_id')
    )
    op.drop_table('users_profiles')
    # ### end Alembic commands ###
