"""added admin action table

Revision ID: a283943a7da9
Revises: c22ba98dbff6
Create Date: 2025-07-03 13:24:15.820372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a283943a7da9'
down_revision = 'c22ba98dbff6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action_log',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_admin_id', sa.String(), nullable=False),
    sa.Column('performed_by_admin_id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['performed_by_admin_id'], ['admins.admin_id'], ),
    sa.ForeignKeyConstraint(['target_admin_id'], ['admins.admin_id'], ),
    sa.PrimaryKeyConstraint('log_id')
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('is_active')

    op.drop_table('admin_action_log')
    # ### end Alembic commands ###
