"""Splitted the users table into users and user profiles

Revision ID: d4deb2ea4a10
Revises: 235a9ed75538
Create Date: 2025-07-11 04:58:17.743771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4deb2ea4a10'
down_revision = '235a9ed75538'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_profile',
    sa.Column('userp_id', sa.String(length=7), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(length=30), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=False),
    sa.Column('profile_pic', sa.String(length=200), nullable=False),
    sa.Column('invite_code', sa.String(), nullable=False),
    sa.Column('marketin_opt_in', sa.Boolean(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('userp_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('invite_code')
        batch_op.drop_column('marketin_opt_in')
        batch_op.drop_column('location')
        batch_op.drop_column('profile_pic')
        batch_op.drop_column('phone_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.VARCHAR(length=30), nullable=True))
        batch_op.add_column(sa.Column('profile_pic', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('location', sa.VARCHAR(length=200), nullable=True))
        batch_op.add_column(sa.Column('marketin_opt_in', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('invite_code', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('date_of_birth', sa.DATE(), nullable=True))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)

    op.drop_table('users_profile')
    # ### end Alembic commands ###
